package qwen

import (
	"webtyp.com/fmt"
	"webtyp.com/llm"
)

// parseToolCalls parses text generated by the model into content and tool calls.
// Text before the first <tool_call> (trimmed of leading/trailing space) is content.
func parseToolCalls(text string, tools []llm.ToolDef) (string, []llm.ToolCall, error) {
	firstCallIdx := fmt.Index(text, tagToolCall)
	var content string
	var toolCallsBlock string

	if firstCallIdx == -1 {
		content = fmt.TrimSpace(text)
		return content, nil, nil
	}

	content = fmt.TrimSpace(text[:firstCallIdx])
	toolCallsBlock = text[firstCallIdx:]

	var calls []llm.ToolCall
	callSeq := 0

	rest := toolCallsBlock
	for {
		startIdx := fmt.Index(rest, tagToolCall)
		if startIdx == -1 {
			break
		}
		endIdx := fmt.Index(rest[startIdx:], tagToolCallEnd)
		if endIdx == -1 {
			return "", nil, fmt.Errf("malformed tool call: missing </tool_call>")
		}
		endIdx += startIdx

		block := rest[startIdx+len(tagToolCall) : endIdx]
		rest = rest[endIdx+len(tagToolCallEnd):]

		callSeq++
		callID := fmt.Sprintf("call_%d", callSeq)

		name, rawParams, err := parseSingleToolCallBlock(block)
		if err != nil {
			return "", nil, err
		}

		var toolDef *llm.ToolDef
		for j := range tools {
			if tools[j].Name == name {
				toolDef = &tools[j]
				break
			}
		}
		if toolDef == nil {
			return "", nil, fmt.Errf("unknown tool call: %s", name)
		}

		jsonInput, err := formatAndValidateParams(rawParams, toolDef.InputSchema)
		if err != nil {
			return "", nil, err
		}

		calls = append(calls, llm.ToolCall{
			ID:    callID,
			Name:  name,
			Input: jsonInput,
		})
	}

	return content, calls, nil
}

type paramKV struct {
	key string
	val string
}

func parseSingleToolCallBlock(block string) (string, []paramKV, error) {
	fnStart := fmt.Index(block, tagFunctionStart)
	if fnStart == -1 {
		return "", nil, fmt.Errf("malformed tool call: missing <function=")
	}
	fnStart += len(tagFunctionStart)

	fnEndTag := ">"
	fnCloseIdx := fmt.Index(block[fnStart:], fnEndTag)
	if fnCloseIdx == -1 {
		return "", nil, fmt.Errf("malformed tool call: unclosed <function=")
	}
	fnCloseIdx += fnStart

	funcName := fmt.TrimSpace(block[fnStart:fnCloseIdx])

	fnBlockEnd := fmt.Index(block[fnCloseIdx:], tagFunctionEnd)
	if fnBlockEnd == -1 {
		return "", nil, fmt.Errf("malformed tool call: missing </function>")
	}
	fnBlockEnd += fnCloseIdx

	paramsBlock := block[fnCloseIdx+1 : fnBlockEnd]

	var params []paramKV
	pRest := paramsBlock

	for {
		pStart := fmt.Index(pRest, tagParameterStart)
		if pStart == -1 {
			break
		}
		pStart += len(tagParameterStart)

		pCloseIdx := fmt.Index(pRest[pStart:], ">")
		if pCloseIdx == -1 {
			return "", nil, fmt.Errf("malformed parameter: unclosed <parameter=")
		}
		pCloseIdx += pStart

		paramKey := fmt.TrimSpace(pRest[pStart:pCloseIdx])

		pEndTagIdx := fmt.Index(pRest[pCloseIdx:], tagParameterEnd)
		if pEndTagIdx == -1 {
			return "", nil, fmt.Errf("malformed parameter: missing </parameter>")
		}
		pEndTagIdx += pCloseIdx

		rawVal := pRest[pCloseIdx+1 : pEndTagIdx]
		if fmt.HasPrefix(rawVal, "\n") {
			rawVal = rawVal[1:]
		}
		if fmt.HasSuffix(rawVal, "\n") {
			rawVal = rawVal[:len(rawVal)-1]
		}

		params = append(params, paramKV{key: paramKey, val: rawVal})

		pRest = pRest[pEndTagIdx+len(tagParameterEnd):]
	}

	return funcName, params, nil
}

type propTypeKV struct {
	name  string
	pType string
}

func formatAndValidateParams(params []paramKV, schemaJSON string) (string, error) {
	propTypes := parseSchemaPropertyTypes(schemaJSON)

	out := []byte("{")
	for i, kv := range params {
		if i > 0 {
			out = append(out, ',', ' ')
		}
		out = appendJSONString(out, kv.key)
		out = append(out, ':', ' ')

		pType := "string"
		for _, pt := range propTypes {
			if pt.name == kv.key {
				pType = pt.pType
				break
			}
		}

		switch pType {
		case "integer", "number":
			v := fmt.TrimSpace(kv.val)
			out = append(out, []byte(v)...)
		case "boolean":
			v := fmt.TrimSpace(kv.val)
			if v == "true" || v == "True" {
				out = append(out, []byte("true")...)
			} else if v == "false" || v == "False" {
				out = append(out, []byte("false")...)
			} else {
				out = append(out, []byte(v)...)
			}
		case "object", "array":
			formatted := reformatJSON([]byte(kv.val))
			out = append(out, formatted...)
		default: // string or unknown
			out = appendJSONString(out, kv.val)
		}
	}
	out = append(out, '}')
	return string(out), nil
}

func parseSchemaPropertyTypes(schemaJSON string) []propTypeKV {
	var res []propTypeKV
	if schemaJSON == "" {
		return res
	}

	src := []byte(schemaJSON)
	propsIdx := fmt.Index(schemaJSON, `"properties"`)
	if propsIdx == -1 {
		return res
	}

	i := propsIdx + len(`"properties"`)
	i = skipWhitespace(src, i)
	if i < len(src) && src[i] == ':' {
		i++
	}
	i = skipWhitespace(src, i)
	if i >= len(src) || src[i] != '{' {
		return res
	}
	i++ // skip '{'

	depth := 1
	for i < len(src) && depth > 0 {
		i = skipWhitespace(src, i)
		if i >= len(src) {
			break
		}
		if src[i] == '}' {
			depth--
			i++
			continue
		}
		if src[i] == ',' {
			i++
			continue
		}
		if src[i] != '"' {
			i++
			continue
		}

		propName, nextI := parseJSONStringValue(src, i)
		i = skipWhitespace(src, nextI)
		if i < len(src) && src[i] == ':' {
			i++
		}
		i = skipWhitespace(src, i)

		if i < len(src) && src[i] == '{' {
			propDescEnd, pType := parsePropertyTypeFromObject(src, i)
			res = append(res, propTypeKV{name: propName, pType: pType})
			i = propDescEnd
		} else {
			i++
		}
	}

	return res
}

func parsePropertyTypeFromObject(src []byte, start int) (int, string) {
	i := start + 1
	pType := "string"
	depth := 1
	inStr := false
	escaped := false

	for i < len(src) && depth > 0 {
		b := src[i]
		if inStr {
			if escaped {
				escaped = false
			} else if b == '\\' {
				escaped = true
			} else if b == '"' {
				inStr = false
			}
		} else {
			if b == '"' {
				if i+6 <= len(src) && string(src[i:i+6]) == `"type"` {
					i += 6
					i = skipWhitespace(src, i)
					if i < len(src) && src[i] == ':' {
						i++
					}
					i = skipWhitespace(src, i)
					if i < len(src) && src[i] == '"' {
						val, nextI := parseJSONStringValue(src, i)
						pType = val
						i = nextI
						continue
					}
				} else {
					inStr = true
				}
			} else if b == '{' {
				depth++
			} else if b == '}' {
				depth--
				if depth == 0 {
					i++
					break
				}
			}
		}
		i++
	}
	return i, pType
}
